name: Feature
description: Create a new feature request
title: 'LUM-XXX: '
labels:
  - feature

body:
  - type: input
    id: feature_name
    attributes:
      label: Feature Name
      placeholder: Configure Application Configuration
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      placeholder: Brief description of the feature...
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      value: |
        - [ ]
        - [ ]
        - [ ]
        - [ ]
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      value: |
        - [ ]
        - [ ]
        - [ ]
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Technical Notes
